runtime: python27
api_version: 1
threadsafe: true
application: marine-potion-146721

inbound_services:
- channel_presence

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
